spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PWD}@${MONGODB_HOST:localhost:27017}/${MONGODB_NAME:shortener-reactive}?${MONGODB_PARAMETERS:authSource=admin}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000, expireAfterWrite=24h
